name: bookworm
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  drift: ^2.25.1
  get_it: ^8.0.3
  path_provider: ^2.1.5
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.31
  drift_flutter: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.25.2
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/